### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by redmushie** [Shock-Link/Firmware#2]
This repo currently has no README.

## Requirements
- [ ] Repository description
- [ ] List compatible hardware
- [ ] Instructions for flashing the firmware
- [ ] Instructions for contributing?

**Comment by LucHeart** [comment]
https://github.com/Shock-Link/Firmware/commit/bdee9340a1c33c1dd7dd289de1c2bc3683ee2730 introduces a README. Anything you would like to add for now?

**Comment by redmushie** [comment]
LGTM for now!
